apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: n8n
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: n8n
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: n8n-ui
      path: /metrics
      interval: 30s
