apiVersion: apps/v1
kind: Deployment
metadata:
  name: kestra
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: kestra
          image: kestra/kestra
          args: ["server", "standalone"]
          ports:
            - containerPort: 8080
          env:
            - name: KESTRA_CONFIGURATION
              valueFrom:
                configMapKeyRef:
                  name: kestra-configuration
                  key: KESTRA_CONFIGURATION
      volumes:
        - name: kestra-data
          persistentVolumeClaim:
            claimName: kestra-pvc