apiVersion: v1
kind: PersistentVolume
metadata:
  name: kestra-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/host/kestra
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kestra-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: kestra-pv
  storageClassName: ""