apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homepage
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    path: apps/homepage
    repoURL: https://github.com/KrishnaChaitanya20/k8s-homelab
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
      enabled: true
    syncOptions: []